version: "3"

services:
  silimasoftware:
    build: .
    env_file:
      - .env
    restart: always
    command: /bin/sh -c "./setup.sh"
    container_name: silimasoftware
    volumes:
      - website_data:/usr/src/app


  silimasoftware_nginx:
    build: ./nginx
    restart: always
    container_name: silimasoftware_nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.silimasoftware_nginx.entrypoints=websecure"
      - "traefik.http.routers.silimasoftware_nginx.tls.certresolver=sslresolver"
      - "traefik.http.routers.silimasoftware_nginx.rule=Host(`alpha.silimasoftware.co.za`)"
      - "traefik.http.services.silimasoftware_nginx.loadbalancer.server.port=80"
    volumes:
      - website_data:/usr/src/app
    depends_on:
      - silimasoftware

  db-silimasoftware:
    image: postgres
    restart: always
    container_name: db-silimasoftware 
    env_file:
      - .env
    volumes:
      - silimasoftware_data:/var/lib/postgresql/data

volumes:
  silimasoftware_data:
  website_data:

networks:
  default:
    external:
      name: hostnet
